name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run Tests
      run: |
        python app/test_main.py

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app .

    - name: Push Docker Image
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-app

    - name: Deploy with Terraform
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve -var access_key=${{ secrets.AWS_ACCESS_KEY }} -var secret_key=${{ secrets.AWS_SECRET_KEY }}

    - name: Notify Success
      run: echo "Deployment completed"
